# Generated by Django 5.0.2 on 2024-02-26 00:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0003_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=7)),
                ('prefectures', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='電話番号はハイフン無しの10桁または11桁の数字で入力してください。', regex='^\\d{10,11}$')], verbose_name='電話番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
