# Generated by Django 5.0.2 on 2024-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0004_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line1',
            field=models.CharField(max_length=100, verbose_name='町名・番地'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, verbose_name='建物名・部屋番号'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=7, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='prefectures',
            field=models.CharField(max_length=10, verbose_name='都道府県'),
        ),
    ]
