# Generated by Django 5.0.2 on 2024-03-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0006_shippingaddress_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
