# Generated by Django 5.0.2 on 2024-03-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
