# Generated by Django 5.0.2 on 2024-03-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0012_payment_card_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
