from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    Top,
    SignupFunc,
    LoginFunc,
    LogoutFunc,
    ProfileView,
    NameEditView,
    CustomEmailView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetFromKeyView,
    CustomPasswordResetFromKeyDoneView,
    AddShippingAddress,
    EditShippingAddress,
    DeleteShippingAddress,
    ShippingAddressList,
    ProductListFunc,
    ProductDetailFunc,
    AddProduct,
    ReductionProduct,
    RemoveProduct,
    OrderView,
    PaymentView,
    ThanksView,
)

urlpatterns = [
    path('', Top.as_view(), name='top'),
    path('accounts/signup/', SignupFunc.as_view(), name='signup'),
    path('accounts/login/', LoginFunc.as_view(), name='login'),
    path('logout/', LogoutFunc.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/name/', NameEditView.as_view(), name='name_edit'),
    path('reset_email/', CustomEmailView.as_view(), name='account_email'),
    path('reset_password/', CustomPasswordResetView.as_view(), name='account_reset_password'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^accounts/password/reset/key/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', CustomPasswordResetFromKeyView.as_view(), name='account_reset_password_from_key'),
    path('password/reset/key/done/', CustomPasswordResetFromKeyDoneView.as_view(), name='account_reset_password_from_key_done'),
    path('add_shipping_address/', AddShippingAddress, name='add_shipping_address'),
    path('edit_shipping_address/<int:id>/', EditShippingAddress, name='edit_shipping_address'),
    path('shipping_address_list/', ShippingAddressList.as_view(), name='shipping_address_list'),
    path('delete_shipping_address/<int:id>/', DeleteShippingAddress, name='delete_shipping_address'),
    path('products/', ProductListFunc.as_view(), name='product_list'),
    path('product/<slug>/', ProductDetailFunc.as_view(), name='product_detail'),
    path('add_product/<slug>', AddProduct, name='add_product'),
    path('reduce/<slug:slug>/', ReductionProduct, name='reduction_product'),
    path('remove/<slug:slug>/', RemoveProduct, name='remove_product'),
    path('order/', OrderView.as_view(), name='order'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
