from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    SignupFunc,
    LoginFunc,
    LogoutFunc,
    ProfileView,
    NameEditView,
    CustomEmailView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetFromKeyView,
    CustomPasswordResetFromKeyDoneView,
    AddShippingAddress,
    EditShippingAddress,
    DeleteShippingAddress,
    ShippingAddressList,
    ProductListFunc,
    ProductDetailFunc,
    AddProductToCart,
    ReductionProduct,
    RemoveProduct,
    OrderView,
    PaymentView,
    ThanksView,
    Search,
    SearchSuggest,
    OrderHistory,
    OrderDetail,
)

urlpatterns = [
    path('signup/', SignupFunc.as_view(), name='signup'),
    path('login/', LoginFunc.as_view(), name='login'),
    path('logout/', LogoutFunc.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/name/', NameEditView.as_view(), name='name_edit'),
    path('accounts/reset_email/', CustomEmailView.as_view(), name='account_email'),
    path('reset_password/', CustomPasswordResetView.as_view(), name='account_reset_password'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password/reset/key/<uidb64>/<token>/', CustomPasswordResetFromKeyView.as_view(), name='account_reset_password_from_key'),
    path('password/reset/key/done/', CustomPasswordResetFromKeyDoneView.as_view(), name='account_reset_password_from_key_done'),
    path('add_shipping_address/', AddShippingAddress, name='add_shipping_address'),
    path('edit_shipping_address/<int:id>/', EditShippingAddress, name='edit_shipping_address'),
    path('shipping_address_list/', ShippingAddressList.as_view(), name='shipping_address_list'),
    path('delete_shipping_address/<int:id>/', DeleteShippingAddress, name='delete_shipping_address'),
    path('', ProductListFunc.as_view(), name='product_list'),
    path('product/<slug>/', ProductDetailFunc.as_view(), name='product_detail'),
    path('add_product/<slug>', AddProductToCart, name='add_product'),
    path('reduce/<slug:slug>/', ReductionProduct, name='reduction_product'),
    path('remove/<slug:slug>/', RemoveProduct, name='remove_product'),
    path('order/', OrderView.as_view(), name='order'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
    path('search/', Search, name='search'),
    path('search-suggest/', SearchSuggest, name='search_suggest'),
    path('order_history/', OrderHistory, name='order_history'),
    path('order_detail/<int:order_id>/', OrderDetail, name='order_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
